=== VoloshynVasyl/Java/Block04_RegExp/src/main/resources/MyPhoneBookSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="phoneBook">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="note">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="surname"/>
                            <xs:element type="xs:string" name="patronymic"/>
                            <xs:element type="xs:string" name="surnameAndInitials"/>
                            <xs:element type="xs:string" name="nickname"/>
                            <xs:element type="xs:string" name="comment"/>
                            <xs:element type="xs:string" name="group"/>
                            <xs:element type="xs:int" name="homePhone"/>
                            <xs:element type="xs:int" name="cellPhone"/>
                            <xs:element type="xs:string" name="secondCellPhone"/>
                            <xs:element type="xs:string" name="email"/>
                            <xs:element type="xs:string" name="skype"/>
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:int" name="index"/>
                                        <xs:element type="xs:string" name="city"/>
                                        <xs:element type="xs:string" name="street"/>
                                        <xs:element type="xs:byte" name="house"/>
                                        <xs:element type="xs:byte" name="apartment"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="fullAddress"/>
                            <xs:element type="xs:string" name="registrationDate"/>
                            <xs:element type="xs:string" name="lastEditDate"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== VoloshynVasyl/Java/Block04_RegExp/src/main/resources/MyPhoneBook.xml
<?xml version="1.0"?>
<phoneBook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MyPhoneBookSchema.xsd">
    <note>
        <name>Vasyl</name>
        <surname>Voloshyn</surname>
        <patronymic>Alexandrovich</patronymic>
        <surnameAndInitials>Voloshyn V</surnameAndInitials>
        <nickname>Ghost</nickname>
        <comment></comment>
        <group>FAMILY</group>
        <homePhone>1235485</homePhone>
        <cellPhone>0630268645</cellPhone>
        <secondCellPhone></secondCellPhone>
        <email>voloshinvasily@gmail.com</email>
        <skype>ghost_181295</skype>
        <address>
            <index>112233</index>
            <city>Kyiv</city>
            <street>Metalistiv</street>
            <house>7</house>
            <apartment>105</apartment>
        </address>
        <fullAddress>112233, Kyiv, Metalistiv, 7, 105</fullAddress>
        <registrationDate>05.12.2017</registrationDate>
        <lastEditDate>05.12.2017</lastEditDate>
    </note>
</phoneBook>
